version: '3.7'

services:
  drupal:
    build: .
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: drupal_pass
    networks:
      - drupal_network

  db:
    image: mysql:8
    container_name: drupal_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal_network

volumes:
  drupal_data:
  db_data:

networks:
  drupal_network:
    driver: bridge
